### PR TITLE
feat(contributor): Added a new contributor to the slide show

### PR DESCRIPTION
**Pull request by spencer-forrest-opt**
A new issue will be created because the contributor 'dsantos', alias @Dougniel, does not have his style sheet linked in the root 'index.html'.

dsantos
index

### CODE REVIEW

**Comment by adriens** [comment]
Thanks a lot @spencer-forrest-opt

**Comment by adriens** [comment]
@spencer-forrest-opt : you do not appear on the slideshow : when on the last slide (@Dougniel ), we're back on the first slide

**Comment by adriens** [comment]
Some GH cahce issue, then it's :ok_hand: 

https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/8

image

image

image

image

Officially welcome to GLIA :clap: :open_hands:

**Comment by spencer-forrest-opt** [comment]
> @spencer-forrest-opt : you do not appear on the slideshow : when on the last slide (@Dougniel ), we're back on the first slide

It works for me at [https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/8/1](https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/8/1)

slideshow

**Comment by spencer-forrest-opt** [comment]
'dsantos' style sheet issue:
https://github.com/adriens/livre-or-collaborateurs-glia-slideshow/issues/67

**Pull request merged**
